### ISSUE TITLE
Simple installation instructions in README

### ISSUE THREAD

**Issue by stevenroose** [dirruk1/gnome-breeze#19]
This may sound stupid, but I have no idea how to install a GTK theme in KDE, especially not right from GitHub.

Could anyone be so glad to add installation instructions to the README file?

Many thanks!

**Comment by Martchus** [comment]
I've added some installation instructions: https://github.com/Martchus/gnome-breeze/blob/6ad3dc7bd63ff62be2a70586563905e6a29a3cb3/README.md

**Comment by ghost** [comment]
Hm, even though we're moving this to KDE's repository soon, I suppose it's fine to add something like this since the README.md likely won't be carried over directly.

Even still, that additional text is somewhat verbose and I always understood ~/.themes to be the preferable directory for local GTK theme installation. Is there a clear advantage to using ~/.local/share/themes?

At any rate, I think I'll merge it and make some small adjustments to the text for now to keep it light.

**Comment by stevenroose** [comment]
What is the find command supposed to do? I cloned the repo in the ~/.local/... folder and installed the KDE GTK Configurator. However, I can't seem to launch it. The package name `kde-gtk-config` is not the binary name and I cant find it in my app menu not System Settings...

**Comment by stevenroose** [comment]
Got it. Arch Wiki helped me out: https://wiki.archlinux.org/index.php/GTK%2B#Configuration_tools

**Comment by Martchus** [comment]
I think you're right. ~/.themes might be preferable. (I personally prefer a system wide installation via package manager.)
