### ISSUE TITLE
No GTK3 breeze / breeze-dark theme found in KDE Plasma 5.4.3 (Debian)

### ISSUE THREAD

**Issue by shmerl** [dirruk1/gnome-breeze#58]
When current master is installed in Debian (I use $HOME/.local/share/themes location), GTK3 themes aren't discovered by **Application Style / GTK Style** (in System Settings).

I know this Plasma is outdated, but Debian testing is stuck with it unfortunately, and it might take a while to get unstuck.

Copying gtk-3.18 to gtk-3.0 provides a workaround for Debian testing at least.

**Comment by ghost** [comment]
Hm- I believe the packages for older versions of Breeze GTK are still available. As such, I'm not certain this should be considered a bug, although we may add a 3.16 folder just in case. Earlier versions aren't supported anyway, and we'll probably eventually lump everything into a single 3.0 folder when GTK versions above 3.20 are common.

The issue with putting an older version of the theme into 3.0 is that future GTK versions may reference that folder instead of 3.20, increasing the maintenance burden and filesize if we're forced to create many folders containing the same theme. So, for the moment, it's undecided which theme should naturally be in the 3.0 folder, as some older versions of DEs appear to rely on its existence to see the theme.

For now, though, we might be able to symlink a few things so the filesize doesn't grow unchecked by all the duplication. I'll keep this issue open for discussion in the meantime.

**Comment by shmerl** [comment]
I tried making a symlink gtk-3.16 → gtk-3.18 and system settings didn't pick it up. gtk-3.0 → gtk-3.18 works though.

It's not really about older versions of breeze-gtk, but about compatibility with older Plasma tools which are still stuck in Debian. Hopefully eventually Debian will move forward (I think Qt 5.6.1 is something they are waiting for).

**Comment by ghost** [comment]
I see- thanks for trying it out and letting me know how it went.

I guess I could symlink 3.20 and newer version folders to the latest theme folder in the future (3.20, 3.22, 3.24 would all link to 3.26 instead of duplicating it, for instance) and place the older theme in gtk-3.0 until we can afford to lump it all together like the GTK 2 theme.

I'll have to check it out and see if it works when GNOME 3.21 starts to churn.

**Comment by Martchus** [comment]
I also noticed that the theme is not discovered by kcm_kdegtkconfig.so under Arch Linux (which ships the latest Plasma 5).

Hence I'm packaging the theme using the following hack: https://github.com/Martchus/PKGBUILDs/blob/master/gnome-breeze/git/PKGBUILD

This basically determines the right version for Arch (which should be always the latest) and installs it as "gtk-3.0". 

However, I wouldn't consider this as an issue of the theme since "fixing" this would lead to the problem scionicspectre already pointed out. You just have to install the version which matches your GTK+3 version into the "gtk-3.0" directory and ignore any other versions. Noting this in the README for unexperienced users should be sufficient.

**Comment by dirruk1** [comment]
just adding an empty gtk-3.0 folder should work

**Comment by ghost** [comment]
@dirruk1 The king returns! If that works we should probably just leave it at that, possibly with a little text file to explain why the folder is empty and what to do if the wrong version of the theme is being loaded (what @Martchus said).

**Comment by dirruk1** [comment]
Are you not on telegram anymore @scionicspectre ?

**Comment by ghost** [comment]
@dirruk1 Ditched the phone so I'll have to figure out another way to get in. There's always email, IRC, Google, and Skype (I've the same username everywhere). I'm guessing I missed some big news on there.

**Comment by shmerl** [comment]
Yes, I confirm that adding empty gtk-3.0 directory fixes it.

**Comment by TassieDevyl** [comment]
I can also confirm that adding an empty gtk-3.0 directory works.

Debian Sid - dist-upgraded on 03 May 2016 @ 10:34 UTC + 10

KDE Frameworks 5.16.0
Qt 5.5.1 (built against 5.5.1)

**Comment by shmerl** [comment]
Since it's fixed now, I'll close it.
