### ISSUE TITLE
Further development of gnome-breeze?

### ISSUE THREAD

**Issue by shmerl** [dirruk1/gnome-breeze#68]
Both branches were pretty inactive in a long time. Do you still plan to work on gnome-breeze going forward?

**Comment by ghost** [comment]
Yeah, the project isn't dead or anything- current development has moved to the KDE repos.

The big feature on the horizon is color theme support, but aside from that the theme doesn't need a great deal of continued development aside from basic maintenance. Of course, there are some notable bugs which we can't resolve without help from GTK and Kwin devs, so those deeper improvements come down to more extensive collaboration between these communities. Given the occasionally frustrating politics around things like this, that will be a long-term goal that is somewhat external to the theme itself.

I'm gonna' go ahead and close this since it's unrelated to the code base, but rest assured the theme will see further development. Given that this is a volunteer project, major changes often happen in brief periods of intense activity, so longer breaks shouldn't be too surprising. If you look through the commit log, you'll see a similar pattern throughout.

**Comment by shmerl** [comment]
I see, thanks. Will this repo be synced with KDE one, or only KDE source will be updated? I suppose the confusion can arise if someone would just monitor this repo, and won't see any updates that appear elsewhere.

**Comment by ghost** [comment]
This won't necessarily sync up with KDE's, but sometimes we use it for experimental features and ideas to avoid cluttering the 'official' branches. I'm unsure if that will continue. Much the same thing happened with the GTK 2 Adwaita theme I worked on- it's still here on Github but it hasn't been touched since it was merged into GNOME about 5 years ago.

There is a mirror of the KDE repo here on Github if you want to stay up to date: https://github.com/KDE/breeze-gtk.
